import { src } from "./image"

export default {
    "size":"medium",
    "width":"100%",
    "grid":1,
    "labelWidth":120,
    "labelShow":true,
    "labelPlacement":"top",
    "labelAlign":"left",
    "items":[
        {
            "_widget":"CARD","size":"medium","width":"100%","grid":3,"labelWidth":"120px","labelShow":true,"labelPlacement":"top","labelAlign":"left",
            "_col":1,"title":"输入组件示例","bordered":true,"_container":true,"_hideLabel":true,
            "items":[
                {"_widget":"IMAGE","_col":3,"height":"auto","maxHeight":"200px","full":true,"scriptTrigger":"click","script":"","_hideLabel":true,src},
                {"_widget":"INPUT","_uuid":"input_001","_text":"项目名称","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","placeholder":"请输入","clearable":false,"show-count":false,"rows":1,"_value":""},
                {"_widget":"NUMBER","_uuid":"money","_text":"项目金额/预算","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","placeholder":"请输入","clearable":false},
                {"_widget":"TAGS","_uuid":"tags_003","_text":"项目成员","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","closable":true,"round":false},
                {"_widget":"BUTTON","_col":3,"label":"自定义脚本：修改项目金额","text":false,"round":false,"disabled":false,"scriptTrigger":"click","script":"form.money = Math.floor(Math.random()*1000000);","_hideLabel":true,"type":"default"}
            ]
        },
        {
            "_widget":"CARD","size":"medium","width":"100%","grid":4,"labelWidth":"120px","labelShow":true,"labelPlacement":"top","labelAlign":"left",
            "_col":1,"title":"选择组件示例","bordered":true,"_container":true,"_hideLabel":true,
            "items":[
                {"_widget":"DATE","_uuid":"date_004","_text":"日期选择","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","placeholder":"请输入","clearable":false,"type":"date","format":"yyyy-MM-dd"},
                {"_widget":"SELECT","_uuid":"select_005","_text":"下拉选择","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","placeholder":"请输入","clearable":false,"filterable":false,"multiple":false,"options":""},
                {"_widget":"RADIO","_uuid":"radio_006","_text":"单选项框","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","button":false,"options":"1|选项一,2|选项二"},
                {"_widget":"CHECKBOX","_uuid":"checkbox_007","_text":"多选项框","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","options":"1|选项一,2|选项二"},
                {"_widget":"SWITCH","_uuid":"switch_008","_text":"开关项框","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","round":true},
                {"_widget":"RATE","_uuid":"rate_009","_text":"星级评分","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","clearable":false,"count":5,"allow-half":false},
                {"_widget":"COLOR","_uuid":"color_010","_text":"颜色选择","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","clearable":false},
                {"_widget":"FILE","_uuid":"file_011","_text":"文件上传","_col":1,"disabled":false,"_watch":false,"_required":false,"_regex":"","_message":"","maxSize":2,"accept":"image/*","dataType":""}
            ]
        },
        {
            "_widget":"CARD","size":"medium","width":"100%","grid":1,"labelWidth":"120px","labelShow":true,"labelPlacement":"top","labelAlign":"left",
            "_col":1,"title":"展示组件示例","bordered":true,"_container":true,"_hideLabel":true,
            "items":[
                {"_widget":"ALERT","_col":1,"title":"提示信息","content":"提示内容","_html":false,"type":"info","bordered":false,"closable":true,"_hideLabel":true},
                {"_widget":"DIVIDER","_col":1,"_value":"静态二维表格（学生信息）","dashed":false,"title-placement":"center","_hideLabel":true},
                {"_widget":"TABLE","_col":1,"bordered":false,"stripe":true,"font-size":14,"textAlign":"left","content":"姓名,性别,学校,专业,年龄,备注\n张三,男,清华大学,微积分,19,\n李四,男,北京大学,广告学,20,保研\n王五,女,广西大学,信息安全,20,\n赵六,男,武汉大学,软件工程,21,开源软件开发者","_hideLabel":true}
            ]
        }
    ],
    "submitText":"保存信息",
    "url":"",
    "okText":"",
    "onLoad":"",
    "onSubmit":"",
    "onChange":"",
    "afterSubmit":"",
    "hides":[],
    "buttons":[]
}
